### ISSUE TITLE
Version mismatches following example

### ISSUE THREAD

**Issue by Gi60s** [byu-oit/terraform-aws-bastion#15]
Maybe I'm using this wrong, but when I copy the code provided in the README.md file and update the variables (and remove the /* and */ block), running `terraform init` produces this error:

```
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.42.0, >= 2.42.*, ~> 3.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints ~> 2.42.0, >= 2.42.*, ~> 3.0
```

I think it has to do with some version mismatch, but I'm not sure why or what to do to fix it.

**Comment by joshgubler** [comment]
Sorry that the docs were out of date @Gi60s . You just need to update your provider block to:
```
provider "aws" {
  version = "~> 3.0"
  region  = "us-west-2"
}
```
